### ISSUE TITLE
Unable to load panel laser.

### ISSUE THREAD

**Issue by drakovych** [DrPacemaker/Voron-Laser-Mod#1]
Could you help to fix the issue?

```
2023-07-27 13:54:00,750 [screen.py:_menu_go_back()] - #### Menu go back
2023-07-27 13:54:00,759 [screen.py:attach_panel()] - Current panel hierarchy: main_panel
2023-07-27 13:54:01,460 [screen.py:_load_panel()] - Loading panel: laser
2023-07-27 13:54:01,460 [screen.py:_load_panel()] - Panel path: /home/pi/KlipperScreen/panels/laser.py
2023-07-27 13:54:01,463 [screen.py:_load_panel()] - object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 277, in _load_panel
    return self.load_panel[panel](*args, **kwargs)
  File "/home/pi/KlipperScreen/panels/laser.py", line 14, in create_panel
    return LaserPanel(*args)
  File "/home/pi/KlipperScreen/panels/laser.py", line 21, in __init__
    super().__init__(screen, title)
  File "/home/pi/KlipperScreen/panels/menu.py", line 24, in __init__
    self.create_menu_items()
  File "/home/pi/KlipperScreen/panels/menu.py", line 74, in create_menu_items
    for i in range(len(self.items)):
TypeError: object of type 'NoneType' has no len()
2023-07-27 13:54:01,464 [screen.py:show_error_modal()] - Showing error modal: Unable to load panel laser Unable to create panel: laser
object of type 'NoneType' has no len()
2023-07-27 13:54:01,489 [KlippyGtk.py:Dialog()] - Showing dialog <Gtk.Dialog object at 0x7f7e05cd40 (GtkDialog at 0x27c959e0)>
--------------------KlipperScreen Log Start--------------------
Git Version: v0.3.3-15-ge8a2d34-dirty
```

**Comment by JasonKwokGJQ** [comment]
I figured it out. The only killperscreen version that will work is v0.3.0, and don't copy the klipper codes provided on the README.md, find the right laser control codes on printer.cfg.

**Comment by mikem4k** [comment]
Same problem Here :D 
is it possible to fix this?
